spring:
  application:
    name: departmentservice
  data:
    mongodb:
#      uri: "mongodb://localhost:27017/sampledb"
      uri: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOSTNAME}:27017/${MONGO_DATABASE}?authSource=admin"

#server:
#  port: 8081

feign:
  name: employee
  url: http://employeeservice/
#  url: http://localhost:8080/

springdoc:
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    enable:
      all: true
    tags:
      application: employeeservice